// Generated by CoffeeScript 1.6.2
window.setPlayerNames = function(text) {
  var element, elements, list, playerBox, _i, _len;

  list = text.split("|");
  elements = document.getElementsByClassName("playerbox");
  for (_i = 0, _len = elements.length; _i < _len; _i++) {
    element = elements[_i];
    playerBox = element.getElementsByClassName("playername")[0];
    playerBox.innerHTML = list.pop();
    if (list.length === 0) {
      break;
    }
  }
  return null;
};

jQuery.fn.center = function () {
    this.parent().css("position","absolute");
    var t = this.parent().css("top");
    var l = this.parent().css("left");
    
    this.css("position","absolute");
    this.css("top", ((this.parent().height() - this.outerHeight()) / 2) + this.parent().scrollTop() + "px");
    this.css("left", ((this.parent().width() - this.outerWidth()) / 2) + this.parent().scrollLeft() + "px");
    return this;
}