// Generated by CoffeeScript 1.6.2
window.setPlayerNames = function(text) {
  var element, elements, list, playerBox, _i, _len;

  list = text.split("|");
  elements = document.getElementsByClassName("playerbox");
  for (_i = 0, _len = elements.length; _i < _len; _i++) {
    element = elements[_i];
    playerBox = element.getElementsByClassName("playername")[0];
    playerBox.innerHTML = list.pop();
    if (list.length === 0) {
      break;
    }
  }
  return null;
};
